const langData = {
  "vi": {
    "m_eye": "Est. 2019 ✦ TP. Hồ Chí Minh, Việt Nam ✦ Phát triển & Thiết kế Sáng tạo",
    "m_tag": "Biên niên sử chính thức về hành trình của một nhà phát triển sáng tạo qua ranh giới kỹ thuật số",
    "m_vol": "TẬP V, SỐ 001",
    "m_edition": "✦ PHIÊN BẢN PORTFOLIO ✦",
    "b_lbl1": "Tin nóng",
    "hl1": "Nhà phát triển sáng tạo định nghĩa lại bối cảnh kỹ thuật số",
    "kicker": "★ Câu chuyện nổi bật — Công nghệ sáng tạo",
    "hl_xl": "Tư duy lập trình, thiết kế & đột phá",
    "deck": "Từ thế giới sáng tạo ngầm của Sài Gòn xuất hiện một nhà phát triển từ chối tách biệt vẻ đẹp khỏi kỹ thuật — tái định nghĩa trải nghiệm trên không gian mạng.",
    "byline": "Bởi Đội ngũ Biên tập ✦ TP. Hồ Chí Minh, Việt Nam",
    "p1": "Trong bối cảnh kỹ thuật số cạnh tranh của Đông Nam Á, một tài năng đặc biệt đã tự khẳng định vị thế hiếm có tại giao điểm của tư duy thiết kế và làm chủ kỹ thuật. Hiệp là một nhà phát triển sáng tạo có các sản phẩm thách thức mọi sự phân loại thông thường — vừa thành thạo trong file Figma lại vừa linh hoạt trong cửa sổ Terminal, tạo ra những trải nghiệm có chiều sâu nghệ thuật lẫn hiệu năng mạnh mẽ.",
    "p2": "Những người từng hợp tác mô tả anh là một người tiếp cận dự án theo cách một nhà báo tiếp cận câu chuyện: thông qua nghiên cứu nghiêm túc, quan sát nhạy bén và một bản năng sắc sảo đối với những chi tiết biến điều bình thường thành điều đáng nhớ.",
    "p3": "Dấu ấn đặc trưng của anh — việc từ chối xem thẩm mỹ và công năng là hai thế lực đối lập — xuất hiện trong mọi dự án. Mỗi tương tác đều mang một giá trị riêng. Mỗi lựa chọn kiểu chữ đều mang một dụng ý. Mỗi dòng code đều phục vụ cho một tầm nhìn lớn hơn.",
    "p4": "Hiện tại anh đang sẵn sàng cho các dự án mới và cơ hội hợp tác trong các lĩnh vực định vị thương hiệu, trải nghiệm tương tác và phát triển sản phẩm full-stack.",
    "pull_q": "\"Thiết kế mà không có code là một giấc mơ. Code mà không có thiết kế là một bộ máy.\"",
    "pull_c": "— Tuyên ngôn Sáng tạo của Hiệp",
    "btn_comm": "Hợp tác viết nên câu chuyện ",
    "photo_cap": "Hiệp — Nhà phát triển sáng tạo & Người kể chuyện kỹ thuật số. Hiện đang làm việc tại TP. Hồ Chí Minh, Việt Nam.",
    "bx_t1": "Kho vũ khí kỹ thuật",
    "bx_t2": "Thành thạo các công cụ",
    "bx_t3": "Sơ lược qua dữ liệu",
    "stat_l1": "Số năm hoạt động",
    "stat_l2": "Dự án hoàn thành",
    "stat_l3": "Khách hàng hài lòng",
    "stat_l4": "Tách cà phê đã uống",
    "bx_t4": "Lĩnh vực chuyên môn",
    "bx_p4": "Chuyên về các trải nghiệm web nơi thiết kế hấp dẫn kết hợp với kỹ thuật mạnh mẽ. Đặc biệt quan tâm đến kể chuyện tương tác, nhận diện thương hiệu và phát triển ưu tiên hiệu năng.",
    "bx_t5": "Trạng thái hiện tại",
    "stat_status": "● Sẵn sàng nhận việc",
    "stat_time": "TỰ DO & TOÀN THỜI GIAN",
    "bx_t6": "Khách hàng gần đây",
    "bx_p6": "Các startup thời trang, công ty SaaS, công ty truyền thông và các studio độc lập tại Việt Nam & Đông Nam Á.",
    "b_lbl2": "Tác phẩm tiêu biểu — Danh mục chọn lọc",
    "hl2": "Những bản tin nổi bật từ thực địa",
    "proj_num1": "Báo cáo thực địa ✦ 001 — Thiết kế thương hiệu",
    "proj_hl1": "Tái cấu trúc bộ nhận diện thương hiệu",
    "proj_body1": "Một đợt cải tổ thương hiệu toàn diện cho một nhãn hiệu thời trang tại Sài Gòn — từ bộ nhận diện hình ảnh đến các điểm chạm kỹ thuật số. Thách thức: làm cho sự sang trọng trở nên dễ tiếp cận mà không làm mất đi bản sắc góc cạnh.",
    "proj_num2": "Báo cáo thực địa ✦ 002 — Full-Stack",
    "proj_hl2": "Nền tảng cộng tác thời gian thực",
    "proj_body2": "Một công cụ hỗ trợ bởi WebSocket xử lý hơn 500 người dùng đồng thời mà không một chút giật lag. Kỹ thuật thuần túy được ẩn mình sau vẻ thanh lịch, và sự thanh lịch được vận hành bởi kỹ thuật.",
    "proj_num3": "Báo cáo thực địa ✦ 003 — Tương tác",
    "proj_hl3": "Trải nghiệm thương hiệu WebGL",
    "proj_body3": "Một trang web nhỏ 3D nằm tại giao điểm của kể chuyện, WebGL và thiết kế chuyển động. Đạt 50,000 lượt truy cập duy nhất trong 72 giờ đầu tiên trên mạng internet.",
    "proj_more": "Đọc toàn bộ câu chuyện ",
    "b_lbl3": "Mục rao vặt — Thư tín",
    "hl3": "Gửi một thông điệp",
    "cl_notice": "✦ Đang mở rộng hợp tác ✦ Sẵn sàng làm việc tự do ✦ Làm việc tại Việt Nam ✦",
    "cl_deck": "Dù bạn có một tầm nhìn thay đổi thế giới hay đơn giản là một bản tóm tắt yêu cầu được chuẩn bị kỹ lưỡng — cuộc trò chuyện đều bắt đầu từ đây.",
    "c_lbl1": "✉ Thư điện tử",
    "c_sub1": "Phản hồi trong vòng 24 giờ",
    "c_lbl2": "◈ Sự hiện diện kỹ thuật số",
    "c_sub2": "Danh mục & Nghiên cứu tình huống",
    "c_lbl3": "◉ Tín hiệu mạng xã hội",
    "c_sub3": "LinkedIn / GitHub / Dribbble",
    "btn_conv": "Bắt đầu cuộc trò chuyện ",
    "f_ornament": "✦  ✦  ✦",
    "f_copy": "The Hiep Times — Tập V, Số 001 — Toàn bộ bản quyền được bảo lưu — 2026",
    "f_pub": "Xuất bản tại Thành phố Hồ Chí Minh, Việt Nam ✦ Được thiết kế có chủ đích & Chăm chút tỉ mỉ",
    "mw_title": "Khuyến nghị thiết bị",
    "mw_desc": "Ấn bản này được thiết kế riêng cho màn hình lớn. Vui lòng sử dụng máy tính để có trải nghiệm thị giác tốt nhất.",
    "mw_btn": "Tiếp tục xem",
  },
  "en": {
    "m_eye": "Est. 2019 ✦ Ho Chi Minh City, Vietnam ✦ Creative Development & Design",
    "m_tag": "The Definitive Chronicle of One Creative Developer's Journey Through the Digital Frontier",
    "m_vol": "VOL. V, NO. 001",
    "m_edition": "✦ PORTFOLIO EDITION ✦",
    "b_lbl1": "Breaking News",
    "hl1": "Creative Developer Redefines the Digital Landscape",
    "kicker": "★ Feature Story — Creative Technology",
    "hl_xl": "A mind that codes, designs & disrupts",
    "deck": "From Saigon's creative underground emerges a developer who refuses to separate beauty from engineering — redefining what the web can feel like.",
    "byline": "By The Editorial Staff ✦ Ho Chi Minh City, Vietnam",
    "p1": "In the competitive digital landscape of Southeast Asia, a singular talent has carved out a rare position at the intersection of design thinking and technical mastery. Hiep is a creative developer whose work defies easy categorization — equally at home in a Figma file as in a terminal window, building experiences that feel as considered as they perform.",
    "p2": "Those who have collaborated with him describe someone who approaches each project the way a journalist approaches a story: through rigorous research, sharp observation, and an instinct for the detail that transforms the ordinary into the memorable.",
    "p3": "His hallmark — the refusal to treat aesthetics and function as opposing forces — shows up in every project. Every interaction earns its place. Every typographic choice carries intent. Every line of code serves the larger vision.",
    "p4": "Currently open to new projects and collaborative opportunities across brand identity, interactive experiences, and full-stack product development.",
    "pull_q": "\"Design without code is a dream. Code without design is machinery.\"",
    "pull_c": "— Hiep's Creative Manifesto",
    "btn_comm": "Commission a Story ",
    "photo_cap": "Hiep — Creative Developer & Digital Storyteller. Currently stationed in Ho Chi Minh City, Vietnam.",
    "bx_t1": "Technical Arsenal",
    "bx_t2": "Also Fluent In",
    "bx_t3": "By The Numbers",
    "stat_l1": "Years Active",
    "stat_l2": "Projects Shipped",
    "stat_l3": "Happy Clients",
    "stat_l4": "Cups of Coffee",
    "bx_t4": "Field of Expertise",
    "bx_p4": "Specializing in web experiences where compelling design meets robust engineering. Particular interest in interactive storytelling, brand identity, and performance-first development.",
    "bx_t5": "Current Status",
    "stat_status": "● Available for Work",
    "stat_time": "FREELANCE & FULL-TIME",
    "bx_t6": "Recent Clients",
    "bx_p6": "Fashion startups, SaaS companies, media agencies, and independent studios across Vietnam & Southeast Asia.",
    "b_lbl2": "Featured Works — Selected Portfolio",
    "hl2": "Notable Dispatches From The Field",
    "proj_num1": "Field Report ✦ 001 &mdash; Brand Design",
    "proj_hl1": "The Brand Identity Overhaul",
    "proj_body1": "A comprehensive rebrand for a Saigon-based fashion label — from visual identity to digital touchpoints. The challenge: make luxury feel accessible without losing its edge.",
    "proj_num2": "Field Report ✦ 002 &mdash; Full-Stack",
    "proj_hl2": "The Real-Time Collaboration Platform",
    "proj_body2": "A WebSocket-powered tool handling 500+ concurrent users without a stutter. Pure engineering disguised as elegance, elegance powered by engineering.",
    "proj_num3": "Field Report ✦ 003 &mdash; Interactive",
    "proj_hl3": "The WebGL Brand Experience",
    "proj_body3": "A 3D microsite at the intersection of storytelling, WebGL, and motion design. 50,000 unique visitors in its first 72 hours on the open web.",
    "proj_more": "Read Full Story ",
    "b_lbl3": "Classified Advertisements — Correspondence",
    "hl3": "Send a Dispatch",
    "cl_notice": "✦  Open for New Engagements  ✦  Available for Freelance  ✦  Based in Vietnam  ✦",
    "cl_deck": "Whether you have a world-changing vision or simply a well-considered brief — the conversation starts here.",
    "c_lbl1": "✉ Electronic Mail",
    "c_sub1": "Response within 24 hours",
    "c_lbl2": "◈ Digital Presence",
    "c_sub2": "Portfolio &amp; case studies",
    "c_lbl3": "◉ Social Dispatches",
    "c_sub3": "LinkedIn / GitHub / Dribbble",
    "btn_conv": "Begin the Conversation ",
    "f_ornament": "✦  ✦  ✦",
    "f_copy": "The Hiep Times — Vol. V, No. 001 — All Rights Reserved — 2026",
    "f_pub": "Published in Ho Chi Minh City, Vietnam ✦ Crafted with Intention & Great Care",
    "mw_title": "Desktop Recommended",
    "mw_desc": "This publication is optimized for larger screens. Please use a desktop for the best visual experience.",
    "mw_btn": "Continue Anyway",
  },
  "ja": {
    "m_eye": "Est. 2019 ✦ ベトナム、ホーチミン市 ✦ クリエイティブ開発 ＆ デザイン",
    "m_tag": "デジタルフロンティアを突き進むクリエイティブデベロッパーの軌跡を記した公式記録",
    "m_vol": "第V巻・第001号",
    "m_edition": "✦ ポートフォリオ特別号 ✦",
    "b_lbl1": "ニュース速報",
    "hl1": "クリエイティブデベロッパーがデジタル環境を再定義",
    "kicker": "★ 特集記事 — クリエイティブテクノロジー",
    "hl_xl": "コード、デザイン、そして変革をもたらす思考",
    "deck": "サイゴンのクリエイティブなアンダーグラウンドから、美とエンジニアリングを融合させ、ウェブの本質を再定義する開発者が現れる。",
    "byline": "編集部 ✦ ベトナム、ホーチミン市",
    "p1": "競争の激しい東南アジアのデジタル市場において、デザイン思考と確かな技術力の交差点に独自のポジションを築いた稀有な才能。ヒエップは、Figmaファイルでのデザインもターミナルウィンドウでの開発も同様にこなし、美しさと高いパフォーマンスを兼ね備えた体験を作り出すクリエイティブデベロッパーです。",
    "p2": "彼と協働した人々は、彼がジャーナリストがストーリーを追うようにプロジェクトに向き合うと語ります。徹底的なリサーチ、鋭い観察眼、そして平凡なものを忘れがたいものへと変えるディテールへの本能を持っています。",
    "p3": "美学と機能性を相反するものとして扱わないという彼の強いこだわりは、すべてのプロジェクトに現れています。すべてのインタラクションに意味があり、すべてのタイポグラフィに意図があり、すべてのコードが大きなビジョンのために書かれています。",
    "p4": "現在、ブランドアイデンティティ、インタラクティブ体験、フルスタック製品開発における新しいプロジェクトやコラボレーションの機会を受け付けています。",
    "pull_q": "「コードのないデザインはただの夢。デザインのないコードはただの機械に過ぎない。」",
    "pull_c": "— ヒエップのクリエイティブマニフェスト",
    "btn_comm": "制作を依頼する ",
    "photo_cap": "ヒエップ — クリエイティブデベロッパー ＆ デジタルストーリーテラー。現在、ベトナムのホーチミン市を拠点に活動中。",
    "bx_t1": "技術スタック",
    "bx_t2": "その他のスキル",
    "bx_t3": "数字で見る実績",
    "stat_l1": "活動年数",
    "stat_l2": "公開プロジェクト",
    "stat_l3": "クライアント数",
    "stat_l4": "飲んだコーヒーの杯数",
    "bx_t4": "専門分野",
    "bx_p4": "魅力的なデザインと堅牢なエンジニアリングが融合したウェブ体験を専門としています。特に対話型のストーリーテリング、ブランドアイデンティティ、そしてパフォーマンス最優先の開発に深い関心を持っています。",
    "bx_t5": "現在のステータス",
    "stat_status": "● お仕事のご依頼受付中",
    "stat_time": "フリーランス ＆ フルタイム",
    "bx_t6": "最近の取引実績",
    "bx_p6": "ベトナムおよび東南アジア全域のファッションスタートアップ、SaaS企業、メディア代理店、独立系スタジオ。",
    "b_lbl2": "注目の実績 — 厳選ポートフォリオ",
    "hl2": "現場からの重要な活動報告",
    "proj_num1": "現地報告 ✦ 001 — ブランドデザイン",
    "proj_hl1": "ブランドアイデンティティの全面刷新",
    "proj_body1": "サイゴンを拠点とするファッションレーベルの大規模なリブランディング。視覚的アイデンティティからデジタルの接点までを担当。課題：尖った個性を失わずにアクセシブルなラグジュアリーを表現すること。",
    "proj_num2": "現地報告 ✦ 002 — フルスタック",
    "proj_hl2": "リアルタイム共同作業プラットフォーム",
    "proj_body2": "WebSocketを搭載し、500人以上の同時接続ユーザーを遅延なく処理するツール。エレガンスをまとった純粋なエンジニアリング、そしてエンジニアリングによって駆動するエレガンス。",
    "proj_num3": "現地報告 ✦ 003 — インタラクティブ",
    "proj_hl3": "WebGLブランドエクスペリエンス",
    "proj_body3": "ストーリーテリング、WebGL、モーションデザインが融合した3Dマイクロサイト。公開後最初の72時間で50,000人のユニークビジターを獲得。",
    "proj_more": "記事をすべて読む ",
    "b_lbl3": "三行広告 — お便り",
    "hl3": "メッセージを送る",
    "cl_notice": "✦ 新規案件受付中 ✦ フリーランス相談可 ✦ ベトナム拠点 ✦",
    "cl_deck": "世界を変えるビジョンであれ、綿密に練られた概要書であれ、すべての対話はここから始まります。",
    "c_lbl1": "✉ 電子メール",
    "c_sub1": "24時間以内にご返信いたします",
    "c_lbl2": "◈ デジタルプレゼンス",
    "c_sub2": "ポートフォリオ ＆ ケーススタディ",
    "c_lbl3": "◉ ソーシャルメディア",
    "c_sub3": "LinkedIn / GitHub / Dribbble",
    "btn_conv": "対話を開始する ",
    "f_ornament": "✦  ✦  ✦",
    "f_copy": "The Hiep Times — 第V巻・第001号 — 不許複製 — 2026",
    "f_pub": "ベトナム・ホーチミン市にて発行 ✦ 意図と細心の注意を払って丁寧に作り込まれた",
    "mw_title": "PC閲覧推奨",
    "mw_desc": "本誌はPC環境に最適化されています。本来のデザインでお楽しみいただくため、PCからのアクセスを推奨いたします。",
    "mw_btn": "このまま進む",
  }
};